name: CI/CD

on: [push]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Deploy
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID_DEV }}
        build-dir: '.'
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: stable
    - name: Deploy
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID_PROD }}
        build-dir: '.'
